### ISSUE TITLE
Dubbel <p> element

### ISSUE THREAD

**Issue by EBok1** [Lmikkers/connect-your-tribe-profile-card#10]
Je zet hier een `<p>` element in een ander `<p>` element dit is niet nodig. 
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/9ef2d6b2109031d3978b262b9b24b9214454cd8c/views/index.ejs#L27

**Comment by Lmikkers** [comment]
Thanks was denk ik een typefoutje, heb het aangepast naar 1 `<p></p>`
