### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Remy2072** [Lmikkers/connect-your-tribe-profile-card#11]
Het main font voor je naam werkt niet, op andere laptops. Probeer de volgende keer het font goed te importeren.
<img width="1792" alt="Scherm­afbeelding 2024-02-09 om 11 55 05" src="https://github.com/Lmikkers/connect-your-tribe-profile-card/assets/70781820/1276ec41-b096-400a-9944-051bb0714b08">
https://fonts.google.com/knowledge/using_type/using_web_fonts_from_a_font_delivery_service

**Comment by Lmikkers** [comment]
Top dankjewel! Ga hier naar kijken en proberen op te lossen!

**Comment by Lmikkers** [comment]
Heb het aangepast, dankjewel!
