### ISSUE TITLE
Dubbele P tags

### ISSUE THREAD

**Issue by Khdulkadir** [Lmikkers/connect-your-tribe-profile-card#5]
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/1f5685e7be5391550b57406a07c591ddb9d22927/views/index.ejs#L27

Er zijn dubbele <p> tags hier. Er kan eentje weggehaald worden.

**Comment by Lmikkers** [comment]
Thanks! Heb het aangepast, was denk ik typefoutje
