### ISSUE TITLE
Van h1 naar h3

### ISSUE THREAD

**Issue by Khdulkadir** [Lmikkers/connect-your-tribe-profile-card#6]
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/1f5685e7be5391550b57406a07c591ddb9d22927/views/index.ejs#L16C5-L17C36

De semantische heading volgorde is van H1 naar H2 naar H3. De H3 in jouw code zou beter een h2 kunnen zijn.

**Comment by Lmikkers** [comment]
Aah dankje! Ga het aanpassen :)
