### ISSUE TITLE
Image 

### ISSUE THREAD

**Issue by EBok1** [Lmikkers/connect-your-tribe-profile-card#9]
Image heeft geen alt attribute. 
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/9ef2d6b2109031d3978b262b9b24b9214454cd8c/views/index.ejs#L9

Kan je oplossen door een `alt` toe te voegen zoals hier:
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/9ef2d6b2109031d3978b262b9b24b9214454cd8c/views/index.ejs#L20
of de `alt` leeg te laten zoals je hier hebt gedaan:
https://github.com/Lmikkers/connect-your-tribe-profile-card/blob/9ef2d6b2109031d3978b262b9b24b9214454cd8c/views/index.ejs#L10

**Comment by Lmikkers** [comment]
Top, thanks heb het aangepast!

**Comment by Lmikkers** [comment]
Top, thanks heb het aangepast!
